//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(EstadoCuentaMetadata))]
    public partial class EstadoCuenta
    {
        public int ID { get; set; }
        public int ResidenciaID { get; set; }
        public int PlanCobroID { get; set; }
        public decimal Monto { get; set; }
        public string Estado { get; set; }
        public System.DateTime Mes { get; set; }
    
        public virtual PlanCobro PlanCobro { get; set; }
        public virtual Residencia Residencia { get; set; }
    }
}
